name: Secure Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Secret in a script
      run: |
        echo "The API key is available to the script"
        # Access the secret value via the environment variable
        ./your_application --api-key="$API_KEY"
      env:
        API_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        API_USER: ${{ secrets.EC2_USER }}
