name: Send Secret Email

on: workflow_dispatch

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: "shobhit.saxena54@gmail.com"
        password: "csnl erkp xtje xphd"
        subject: "Your GitHub Secret"
        to: "shobhit.saxena54@gmail.com"
        from: "GitHub Actions"
        body: |
          Secret content:
          ${API_KEY}
      env:
        API_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        API_USER: ${{ secrets.EC2_USER }}
